# Version of the application (not a standard Kubernetes field, custom use)
apiVersion: v1  

# Resource type is a Service
kind: Service

# Metadata about the Service
metadata:
  # The name of the Service
  name: jv-app-service  

spec:
  # Service type defines how it is exposed (NodePort makes it accessible outside the cluster)
  type: NodePort  

  # Ports that the Service exposes
  ports:
  - name: http          # Human-readable name for the port
    port: 80            # Port the Service listens on (for external clients)
    targetPort: 8080    # Port on the Pods that the Service forwards traffic to
    protocol: TCP       # Protocol used (default is TCP)

  # Selector specifies which Pods this Service applies to
  selector:
    app:
      jv-app-deploy     # This label should match a label on the target Pods
